# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

match_seq_ext_Rcpp <- function(query_peps, ref_list, scorematrix, debug = FALSE) {
    .Call(`_quickMHC_match_seq_ext_Rcpp`, query_peps, ref_list, scorematrix, debug)
}

